### PR TITLE
Improve zug

### PR DESCRIPTION
**Pull request by uilianries**
Some improvements to accept your recipe in Conan Center Index

### CODE REVIEW

**Comment by BlueSolei** [comment]
Thanks a lot for all the great improvements :-)
Two things I see:
1. by changing the setting to `settings = ("compiler", "arch", "os", "build_type")`, you made the recipe depend on `arch`, `os` and `build_type`, which this library doesn't depend on them at all (you didn't use these flags in the recipe).
I see you use:
```cpp
    def package_id(self):
        self.info.header_only()
```
but maybe it's best to be explicit in that this package only depends on the compiler and std?
which brings me to the next issue,
2. the only dependency is in the compiler, its version, and the c++ std.
the code you added is great, but why did you remove the dependency over `Zc:externConstexpr` when using VS?
This flag is needed when we use VS in C++14.
So I can't just use the `self.info.header_only()` trick as I need different version for VS compiler (with the flag)

**Comment by uilianries** [comment]
1. Use FULL settings ever. It will be the only way for Conan V2 which is closer to be released. You should manipulate the package ID on `package_id` method, so does not matter if you are using full settings.

2. Usually we take compiler flags as patch, or even from upstream. I see this is not the case, Zug has no more updates and that flag is too small for a patch. I just reverted to the previous cxxflags.

**Comment by BlueSolei** [comment]
1. cool
2. how exactly do you take the compiler flags as a patch? from where?
Usually, they are part of the build system scripts (here CMake target) but how do you extract them from there? and to where?
 I fill I miss a big part of Conan here :-| do you have an example? a link to docs?

**Comment by uilianries** [comment]
2. Create a patch to change directly the upstream's cmake. For this specific case, externConstexpr is known: https://github.com/arximboldi/zug/issues/26#issuecomment-824004036

About patch example, there are tons in Conan Center Index, just search for "patches". Anyway, it's documented [here](https://github.com/conan-io/conan-center-index/blob/154c9edca773d52a790d917bf2c0b95796a7ce7b/docs/how_to_add_packages.md#conandatayml) and [here](https://github.com/conan-io/conan-center-index/blob/ceacbd2c23f3de8c447c86f51280c5f6484acc90/docs/reviewing.md#applying-patches)

**Comment by BlueSolei** [comment]
I understand patching the library code if we can't change it, but AFAIK this is not the issue here.
The issue here is with compiler flags when you use the library.
I need a way to get these flags from the library to the project which uses the Zug's Conan package.
How do I do that?
My understanding is that I need to put these flags in the recipe, as we did here:
```cpp
    def package_info(self):
        if is_msvc(self):
            self.cpp_info.cxxflags = ["/Zc:externConstexpr"]
```
What other way does the library have which can be taken by the recipe and put in the package so a client can import the package?
What am I missing?

The link you put, tells the programmer to add this flag **manually** to his build script which uses Zug.
Or, the flag can be put in the `CMakeLists.txt` file, as a compiler option to the Zug target, but that means I will need to package that file too and add it as a CMake module, but that will only work for someone who imports the package through CMake.
Again, I fill I miss a fundamental thing here.

**Comment by uilianries** [comment]
btw, about settings: https://github.com/conan-io/conan-center-index/blob/154c9edca773d52a790d917bf2c0b95796a7ce7b/docs/packaging_policy.md#settings

> What other way does the library have which can be taken by the recipe and put in the package so a client can import the package?

https://docs.conan.io/en/latest/reference/conanfile/methods.html#cpp-info

You already did. When passing `cxxflags`, any Conan [generator](https://docs.conan.io/en/latest/reference/generators.html) will inject those flags in the generated file.

**Pull request merged**
